name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          # GITHUB_ENV file is sourced by subsequent steps
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          # ENV is 'beta' if it's a pre-release or contains 'beta' in name
          if [[ "${{ github.event.release.prerelease }}" == "true" || "${{ github.event.release.tag_name }}" =~ .*beta.* ]]
          then
            echo "ENV=beta" >> $GITHUB_ENV
          else
            echo "ENV=prod" >> $GITHUB_ENV
          fi
      - name: Show the results
        run: |
          echo GITHUB_REF_NAME = /$GITHUB_REF_NAME/
          echo "VERSION is /$VERSION/"
          echo "ENV is /$ENV/"
      - name: Update GitHub Release with AMI information
        uses: vmware-tanzu-learning/github-release@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          body: "Testing the new release plugin with $GITHUB_REF_NAME"

